# Generated by Django 3.0.8 on 2021-03-16 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('options', models.ManyToManyField(related_name='options', to='menu_manager.MenuOptions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeesMenuAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=64)),
                ('comentaries', models.CharField(max_length=64)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='menu_manager.Menu')),
                ('menu_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='menu_manager.MenuOptions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
