# Generated by Django 3.0.8 on 2021-03-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesmenuanswer',
            name='comentaries',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='employeesmenuanswer',
            name='employee_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='employeesmenuanswer',
            name='menu_option',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='menu_manager.MenuOptions'),
        ),
    ]
