# Generated by Django 3.0.8 on 2021-03-18 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0003_auto_20210316_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.RemoveField(
            model_name='employeesmenuanswer',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='employeesmenuanswer',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='menu_manager.Employee'),
        ),
    ]
