# Generated by Django 3.0.8 on 2021-03-18 21:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0004_auto_20210318_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentaries', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='start_date',
            field=models.DateField(db_index=True, unique=True, verbose_name='start date'),
        ),
        migrations.RenameModel(
            old_name='MenuOptions',
            new_name='Options',
        ),
        migrations.DeleteModel(
            name='EmployeesMenuAnswer',
        ),
        migrations.AddField(
            model_name='answer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='menu_manager.Employee'),
        ),
        migrations.AddField(
            model_name='answer',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='menu_manager.Menu'),
        ),
        migrations.AddField(
            model_name='answer',
            name='menu_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='menu_manager.Options'),
        ),
    ]
