# Generated by Django 3.0.8 on 2021-03-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0005_auto_20210318_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='menu_manager.Employee'),
        ),
    ]
