# Generated by Django 3.0.8 on 2021-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0006_auto_20210318_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
