# Generated by Django 3.0.8 on 2021-03-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0007_menu_is_sent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
