# Generated by Django 3.0.8 on 2021-03-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0008_auto_20210321_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='menu_manager.Employee'),
            preserve_default=False,
        ),
    ]
